In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

from mape_k import config

2026-05-09 16:16:23.175 | INFO     | mape_k.config:<module>:11 - PROJ_ROOT path is: C:\Users\Ivan\Documentos\MIoT_AI\computo_autonomo\Autonomic-Computing-HW3\mape-k

## Reading data

In [2]:
data_path = config.RAW_DATA_DIR / "sensor1.csv"
data_df = pd.read_csv(data_path)
data_df.head()

,Unnamed: 0,timestamp,vibration_x,vibration_y,vibration_z,class,level,Phase
0,0,2026-03-26 01:48:24.192396,0.002457,0.006754,0.005176,Velocidad 2,2,Phase A
1,1,2026-03-26 01:48:25.192406,0.002526,0.007503,0.005433,Velocidad 2,2,Phase A
2,2,2026-03-26 01:48:27.192423,0.002442,0.006478,0.005226,Velocidad 2,2,Phase A
3,3,2026-03-26 01:48:29.192408,0.002494,0.006214,0.004962,Velocidad 2,2,Phase A
4,4,2026-03-26 01:48:31.192318,0.002477,0.006932,0.005097,Velocidad 2,2,Phase A

### Data cleaning

In [3]:
data_df.columns

Index(['Unnamed: 0', 'timestamp', 'vibration_x', 'vibration_y', 'vibration_z',
       'class', 'level', 'Phase'],
      dtype='str')

In [4]:
cols_to_use = ["timestamp", "vibration_x", "vibration_y", "vibration_z"]

data_df = data_df[cols_to_use]

data_df.head()

                    timestamp  vibration_x  vibration_y  vibration_z
0  2026-03-26 01:48:24.192396     0.002457     0.006754     0.005176
1  2026-03-26 01:48:25.192406     0.002526     0.007503     0.005433
2  2026-03-26 01:48:27.192423     0.002442     0.006478     0.005226
3  2026-03-26 01:48:29.192408     0.002494     0.006214     0.004962
4  2026-03-26 01:48:31.192318     0.002477     0.006932     0.005097

In [ ]:
data_df = data_df.set_index("timestamp")